steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gdg-workshop-259519/gdg-workshop:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gdg-workshop-259519/gdg-workshop:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'gdg-workshop', '--platform=managed', '--region=europe-west1', '--image=gcr.io/gdg-workshop-259519/gdg-workshop:$SHORT_SHA']
